= Dog Sitting Ernie: Oh the Fun You'll Have!
:toc: left
:icons: font

== 🐾 It's Ernie Time!

Hello, and thank you for watching Ernie!

Ernie is a 4-year old Australian Labradoodle who
loves people,
gets along with other dogs,
and desperately wants to play with cats.
As far as Doodles go, Ernie is fairly mellow,
but like every dog, he has moments of exuberance.

This guide is written with the intent to help you better understand Ernie for his and your benefit.

=== 🐕 Personality

Ernie is a sweetie who loves from afar.
He loves to be around people, but he has a bubble of personal space around him.
If you try to snuggle him and he resists, don't take it personally:
he just likes his space.
We chalk it up to him being hot-bodied.

Although usually quiet, Ernie will sound the alarm when
he spots the mail carrier,
hears your front gate open,
or sees other dogs walk by from an inside window.
His bark is surprisingly loud and guttural.
This makes him a great guard dog.
Turning on a TV and setting the volume to low may be enough to cover up those suspicious sounds.
(He enjoys the PBS Kids channel.)

His bark is much bigger than his bite,
and this is further magnified by his skittishness.
Ernie has some triggers that cause him to be to skeptical and uncertain about a person.
This usually manifests by Ernie
approaching the subject (e.g., the person),
wagging his tail (or lowering his tail),
and barking while running toward and away from the subject.
It's not always clear what causes him such grief,
but in the event that it happens,
reassure him that everything is okay by saying, "`Ernie, <<command-its-okay,it's okay>>,`" in a sweet and gentle tone.
Repeat the saying while walking toward the subject.
Ernie's intuition will kick in,
and he will begin to walk towards the subject,
offering kisses to atone for any stress he may have caused.

== 🏠 Introducing Ernie to Your Home

As Ernie becomes part of your home, he will do a lot of sniffing around.
He will explore as much as he can to understand his new surroundings.
If there is food on the floor, he will find and eat it!
He will also inspect all the dog toys he can.
The first time he goes in your yard, he will do a fair bit of marking.

Here are a couple of things you can do to ensure Ernie's introduction to your home goes well.

.To-dos before Ernie enters your home for the first time
* If you don't want Ernie to go into a room, block it off
  (e.g., close the entry door, block the entry with a gate)
* Put away garbage cans or at least put a lid on them
* Put away your dog's toys, bones, and treats (unless they're fair game)

Doing these simple things manages expectations and ensures that Ernie is able to explore safely.

== 📝 Daily Routine

Below is the schedule typically followed at home on any given day.

[TIP]
====
Ernie is a pretty easy-going dog.
Don't treat this schedule as a list of things you must do.
Instead, use it as a guide and to better understand what Ernie may be expecting.
====

.Morning
* 6:30 AM -- <<command-get-busy,Potty>>, followed by breakfast
* 9:00 AM -- Walk and <<command-poop-poop,the other potty>>

.Afternoon
* 12:00 PM -- Dental bone

.Evening
* 3:30 PM -- Walk
* 6:00 PM -- Dinner!
* 7:00&thinsp;&ndash;&thinsp;9:00 PM -- Post-dinner zoomies, play, and bonding

=== 🌄 Morning

Ernie may get close to you in the morning and snuggle.
In fact, pretty much the only time he is willing to snuggle is in the morning (hint: take advantage of it!).

If you awake to the sound of Ernie licking the bed sheets (or you!), he likely needs to relieve himself.
We believe this is a coping mechanism for holding his bladder.

=== 🚽 Potty Time

When dropping off Ernie, you may receive doorbells.
Ernie has been trained to ring these bells when he has to go potty.
Simply hang the bells from the handle of the door that you want Ernie to go out of.
Be sure that Ernie watches you put the bells on the door so he knows what door to go to.
For good measure, after hanging the bells, give them a ring and open and close the door.
That's it!

[NOTE]
====
Ernie almost always goes #2 when he's on a walk.
If you walk him in the morning and evening,
you likely won't have to worry about cleaning up his love offerings in your back yard.
====

=== ⚽ Playtime Activities

Ernie loves to play fetch, especially with a squeaky ball.
He really likes it when you kick the ball, but be careful:
Ernie likes to get real close to the ball as you kick it!

=== 🏃 Leaving Ernie Home Alone

Ernie can be left alone in your home for up to five hours.
Before leaving him, close the doors or block off the entryways to rooms you don't want him in.
If you're going to leave food on the counters, push it back so that he can't reach it.
Also, before you go, take him outside and say, "`<<command-get-busy,Get busy>>.`"

The best way to leave Ernie is to decisively walk out the door without interacting with him.
If he senses you're preparing to leave, he may whine or bark.
If you feel like you need to calm him down before leaving,
try the "`I'm Leaving Protocol`":
Tell Ernie to <<command-wait,wait>>,
spread a handful of treats around the house,
go to the door you will be exiting through,
say, "`<<command-im-leaving,I'm leaving>>. <<command-take-it,Take it!>>`".
Exit while he searches for the treats.

=== 💤 Bedtime

Before heading to bed, there are two things that are usually done.

First, be sure that Ernie goes potty.
The routine we use is to turn off the TV,
say the phrase, "`time for bed, time to <<command-get-busy,get busy>>,`"
and let him outside.
If he looks a little dazed and confused -- likely because you woke him -- then repeat, "`<<command-get-busy,get busy>>`"
Keep insisting until he goes potty.
If he doesn't go before you turn in for the time, he will almost certainly wake you up around 5 AM to go.

Second, give him a couple of small treats.
This helps settle his stomach overnight.
On rare occasions, he has vomited frothy liquid in the morning.
His veterinarian believes this is due to a build up of excessive stomach acid.
Giving him a couple of small treats before bedtime gives something for that acid to work on while he sleeps.

Ernie sleeps on our bed at home, so he will likely want to be on the bed with you.
If you prefer for him to be on the floor of your bedroom, move his bed to your room.
If this is not desirable, you will need to close your bedroom door.
He may whine a little bit, but don't give in.
He will eventually find another spot in the house to settle down for the night.

== 🍲 Feeding & Amounts

Ernie is to be fed two meals daily, roughly 12 hours apart.
Each meal is to be 1/2 cup of the provided dry kibble served in his slow feeder bowl.

Ernie has the stomach of a Labrador Retriever.
He will eat whatever you are eating,
and he will eat until he becomes sick.
His brain and stomach are literally disconnected (at least that's what we think 😅).
By the way he acts, it may be tempting to think you didn't give him enough to eat,
but if you fed him the above amount of kibble, then don't worry, he's fine.

However, there are healthy ways to supplement his diet:

.Supplemental feeding
* Diced apple slices
* Diced cucumber
* Diced zucchini
* Training treats

If you do decide to supplement his diet with the above suggestions,
use it as an opportunity to exercise the commands he knows.
We prefer that he has to "`work`" for his extra feedings.

== 💬 Communicate With Ernie!

Ernie knows multiple languages.
Most of the English phrases he knows can be substituted with physical gestures.
Whichever language you decide to use (phrase or gesture), say his name before issuing the command.
This will grab his attention and set him up for success.

When he performs the desired response, say "`Yes`" in an excited tone.
This is his marker word: when he hears this, he knows he did the right thing and will be rewarded.
Follow the marker word with either a treat or some good rubs.

[TIP]
====
If you issue a command to Ernie while he is giving you his full attention and he does not respond,
try not to repeat the command.
Repeating the command multiple times in a short amount of time diminishes its significance.
Instead, change your presence to make it clear you are expecting something from him:
stand up a little taller,
or move your head up _or_ down (don't nod).
If giving a gesture, gently emphasize it by moving your hand up _or_ down (don't wave).
The point of this is to give him time to think and process the situation.
It also asserts dominance in a non-aggressive way.
If he doesn't respond as you expect, then repeat the command.
====

.Ernie's vocabulary
[cols="2,5,5"]
|===
|Phrase |Gesture |Desired Response

|Bring it back
|Stretch one arm out, bend at the elbow and bring your hand back to your shoulder
|Brings whatever he has back to you (e.g., a ball or toy).
Often used when playing fetch.
Fallback to "`<<command-come,come>>`".

|[[command-come]]Come
|Stretch arm out to side and make a fist. As Ernie comes closer, lower fist in front of you.
|Comes to you and places his nose near the fist.

|Down
|Make a fist in one hand, turn hand palm-side down, lower fist slightly
|Lay down, eyes looking at you

|Drop it
|_None_
|Drop whatever is in his mouth

|[[command-get-busy]]Get busy
|_None_
|Go to the bathroom (usually pee)

|Go for a walk
|_None_
|Get ready for a walk!

|Halt
|_None_
|Stops moving.
Best used on walks (e.g., stopping before crossing a street).
Often followed by "`<<command-wait,wait>>`" when off leash to emphasize the desired response.

|Hop up
|With your palm facing upwards, extend your hand over the object you want Ernie to hop up onto.
Move hand upwards.
|Hop up onto the object under your hand (e.g., bed, couch, tree stump)

|[[command-im-leaving]]I'm leaving
|_None_
|Prepare to be left alone

|[[command-its-okay]]It's okay
|_None_
|Reduce suspicion or anxiety associated with whatever he is focused on

|Jump
|Open hand, turn palm to sky, move hand up towards sky in a quick movement
|Jumps, usually up and at the person

|[[command-leave-it]]Leave it
|_None_
|Leave whatever he is getting into or going after.
Often used on walks when he sees cats or squirrels.

|[[command-other-way]]Other way
|Extend hand out, point a finger down, rotate finger counter clockwise
|Turns 360&deg; counter clockwise.
Often preceded by "`<<command-turn-around,turn around>>`".

|Park it
|Point in direction of mat
|Goes to mat and lies down

|[[command-poop-poop]]Poop, poop
|_None_
|You already know

|Sit
|Pinch all fingers of one hand together to form a point, turn the hand point-side up
|Butt to the ground, eyes looking at you

|Stand
|Pinch all fingers of one hand together to form a point, turn the hand point-side up, move the hand upwards
|Stand on hind legs, usually with front legs raised to the sky

|Take it
|_None_
|Takes whatever the subject of the action is (e.g., a treat or toy)

|[[command-turn-around]]Turn around
|Extend hand out, point a finger down, rotate finger clockwise
|Turns 360&deg; clockwise.
Often followed by "`<<command-other-way,other way>>`".

|[[command-take-it]]Take it
|Point towards the object that he is to pick up
|Pick up something in his mouth

|[[command-wait]]Wait
|Open one hand, fingers spread, palm facing Ernie
|Waits until you approach him and touch his collar
|===

=== 👎 Reprimand

Ernie has been trained with positive enforcement and redirection techniques.
If he is in a place he shouldn't be, redirect him to the place where he should be and block off the place where he was.
If he is getting into something he shouldn't be, redirect his energy into playing with a toy.
If that fails, verbalize a stern "`Ah Ah`" and remove him from the situation.
The goal is set him up for success.
He may look like a Muppet, but he's actually pretty intuitive and smart.

[WARNING]
====
We didn't train him to respond to "`no,`" so repeating "`no`" won't cause the response you're looking for.
====

== 😊 Nicknames

Ernie has many nicknames around the house.
Here are some of them.

.Nicknames
* Black Bear or BB
* Ernst
* Sir Sighs A Lot

== 🏥 Veterinarian Contact

Dr. Brenda Brown-Carlson, DVM +
Mt. Scott Animal Clinic +
8401 SE Ellis Street +
Portland, OR 97266 +
(503) 777-3919

== 🙋 FAQs

=== What dog food does Ernie eat?

Ernie eats 1/2 cup of https://frommfamily.com/products/dog/gold/dry/adult-gold/[Fromm's Adult Gold dry kibble,window=_blank] twice daily, roughly 12 hours apart.

=== Why does Ernie's butt smell like fish?

Anal glands have feelings too.
After a couple of good 💩s, his butt should be back to smelling like ass.

=== Why is Ernie sitting close to me and staring like he wants something?

Is it sometime around 9 AM or 3:30 PM?
If so, Ernie is likely expecting to go on a walk.
Is it sometime around 5 PM?
If so, he is likely looking for dinner (even though he gets fed at 6 PM).

=== Why doesn't Ernie snuggle with me?

Ernie loves from a distance.
The best time to snuggle him is in the morning.

=== Can I feed Ernie from the dinner table?

Please don't.
We have worked hard to train Ernie to not beg while we eat at the table.

=== Can I feed Ernie leftovers?

Leftover kibble? Yes, but Ernie doesn't leave leftovers 😂.
Leftover human food? No.

=== Does Ernie have any food restrictions?

Beef-based treats seem to not agree with him anymore, so avoid those if you can.
If you think he is having a bad reaction to something he ate,
please <<_veterinarian_contact,contact his Veterinarian>>.

=== Does Ernie follow a grain-free diet?

No.

=== Why did Ernie develop loose stool or diarrhea?

This usually happens if his diet is too diverse.
If you have been feeding him a variety of different treats,
dial it back so he's just getting his kibble and training treats.

=== Ernie seems to be aggressive towards other dogs while on walks. What's up with that?

This is relatively new behavior.
The best way to keep this from happening is to carry treats with you while walking him.
If you see a dog that is the size of Ernie or larger, distract him with treats as you walk by the dog.
Try to start this distraction before Ernie becomes interested in the other dog.
If Ernie isn't responding to the treats, sternly say "`Ernie, <<command-leave-it,leave it>>.`"

=== Can I take Ernie to the dog park?

Yes.
Ernie does very well off leash.
He can get kind of grumpy with larger, fluffier dogs, but we've never had an issue at a dog park.
